# -*- coding: utf-8 -*-
"""Roll no 6_Set 4_Question2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TjTgT5zB5lqUPUCjORKk1Wcclia39ulD
"""

#Roll no 6, 10 marker questions, SET 4#

# Q1) Write a python program that accepts a sentence from the user and counts the number of vowels, consonants, digits and blank spaces present in it, then print all four counts.#

sentence = input("Enter a sentence :")
vowels = 0
consonants = 0
digits = 0
spaces = 0
vowel_list = "aeiouAEIOU"

for char in sentence:
  if char.isdigit():
    digits += 1
  elif char.isspace():
    spaces += 1
  elif char.isalpha():
    if char in vowel_list:
      vowels += 1
    else:
      consonants += 1

print(f"Vowels: {vowels}")
print(f"Consonants: {consonants}")
print(f"Digits: {digits}")
print(f"Blank spaces: {spaces}")

"""Q2) Write a python program to check whether a given year is a leap year, applying the full rule: a year is a leap year if it is divisible by 4, Except century years(divisible by 100), which must also be divisible by 400 to be a leap year."""

year_str = input("Enter a year: ")
try:
  year = int(year_str)
  if (year % 400 == 0) or (year % 4 == 0 and year % 100 != 0):
    print(f"{year} is a leap year.")
  else:
    print(f"{year} is not a leap year.")
except ValueError:
  print("Invalid input.")