# -*- coding: utf-8 -*-
"""Session 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wmpHfYdB9WE-jpVEsYpEsjeVGArw1DrK
"""

l = [["Program"], ["Python"], ["Example"]]
for i in l:
  for j in i:
    for b in j:
      print(b)
    print()

num = int(input("Enter a number"))
original = num
total = 0
while num > 0:
  digits = num % 10
  total += digits
  num = num // 10
print(F"The sum of digits of {original} = {total}")

count = 1
while True:
  print(count)
  count += 1
  if not(count<=3):
    break

num = int(input("Enter a number: "))
i = 0
while True:
    print(f"{num} x {i} = {num*i}")
    i+=1
    if(i>=11):
        break
