# -*- coding: utf-8 -*-
"""Session 8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ki97Juqf-PhluCNnU2OzlqNgVq54wtNO
"""

numbers = [4, 8, 15, 16, 23, 42]
target = 16
for n in numbers:
  if n == target:
    print("found", target)
    break
print("checked", n)

for i in range(1, 11):
  if i % 2 == 0:
    continue
  print(i, end= " ")

for i in range(1, 6):
  if i == 3:
    pass
  print(i)

correct_password = "python123"
for attempt in range(1,4):
  entered = input(f"Attempt {attempt}: Enter password: ")
  if entered == correct_password:
    print("Access granted!")
    break
  else:
    print("Access denied -- too many attempts")

"""1) **QUESTION 1**"""

for number in range(1, 51):
  if number % 5 == 0 and number % 7 == 0:
    print(f"Found a number divisible by both 5 and 7: {number}")
    break
  print(number)

"""2) **QUESTION 2**"""

for i in range(0, 31):
  if i % 3 == 0:
    continue
    print(i)