# -*- coding: utf-8 -*-
"""Session 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TuSL1MQ6PTQ583fWRgJxS8Si7zH5qyky
"""

rows = 5
for i in range(1, rows + 1):
  for j in range(i):
    print("+", end"-")
    print()

for i in range(1, 6):
  print(i, "->", i**2)

for i in range(0, 20, 5):
  print(i, ends=" ")
print()
for i in range(0, 10, -5):
  print(i, end = " ")

"""1) **QUESTION 1**"""

for i in range(0, 51):
  print(i)

"""2) **QUESTION 2**"""

num = int(input("Enter a number: "))
i = 0
while True:
    print(f"{num} x {i} = {num*i}")
    i+=1
    if(i>=11):
        break

"""3) **QUESTION 3**"""

for i in range(1,5):
  print(" " * (4-i), end = " ")
  for j in range(1, i+1):
    print(j, end=" ")
  print()