# -*- coding: utf-8 -*-
"""session 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12KVe08LFoj8rqNidwCpJNIqxOunqoLqL
"""

I = 90210
password = 12345678
ID = int(input("Enter ID : "))
Pass = int(input("Enter Password : "))
if ID == I and Pass == password:
    Name = input("Enter Name: ")
    Surname = input("Enter Surname: ")
    Sap_ID = int(input("Enter Sap ID: "))
    mobile = int(input("Enter Phone number: "))
    Course = input("Enter Course: ")
    College = input("Enter College: ")

else:
    print("Incorrect ID or password")

item_name = input("Enter item name: ")
item_price = float(input("Enter item price: "))
item_quantity = int(input("Enter item quantity: "))
item_total = item_price * item_quantity
print(f"{"Attribute":<15} {"Value":<10}")
print(f"{"Item Name:":<15} {item_name:<10}")
print(f"{"Item Price:":<15} {item_price:<10.2f}")
print(f"{"Item Quantity:":<15} {item_quantity:<10}")
print(f"{"Item Total:":<15} {item_total:<10.2f}")

num = int(input("Enter a number: "))

num = int(input("Enter a number: "))
if num % 3 == 0 and num % 5 == 0:
    print(f"{num} is divisible by both 3 and 5.")
elif num % 3 == 0:
    print(f"{num} is divisible by 3 but not by 5.")
elif num % 5 == 0:
    print(f"{num} is divisible by 5 but not by 3.")
else:
    print(f"{num} is not divisible by either 3 or 5.")